config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :users
  resources :alphas
  resources :articles
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # root "application#home"
  root "pages#home"
  get "about" , to: "pages#about"
end

app/models/alpha.rb
class Alpha < ApplicationRecord
  belongs_to :user
  validates :title , presence: true , length: {minimum: 1 , maximum: 76}
  validates :description , presence: true , length: {minimum: 3 , maximum: 76}
  validates :user_id , presence: true
end

app/controllers/alphas_controller.rb
class AlphasController < ApplicationController
  before_action :set_alpha, only: [:show, :edit, :update, :destroy]

  # GET /alphas
  # GET /alphas.json
  def index
    @alphas = Alpha.all
  end

  # GET /alphas/1
  # GET /alphas/1.json
  def show
  end

  # GET /alphas/new
  def new
    @alpha = Alpha.new
  end

  # GET /alphas/1/edit
  def edit
  end

  # POST /alphas
  # POST /alphas.json
  def create
    # debugger prevent execution and debug
    # debugger
    @alpha = Alpha.new(alpha_params)
    @alpha.user = User.first
    if @alpha.save
      flash[:notice] = "article was successfully created"
      redirect_to alpha_path(@alpha)
    else
      render 'new'
    end
  end

  # PATCH/PUT /alphas/1
  # PATCH/PUT /alphas/1.json
  def update
    if @alpha.update(alpha_params)
      flash[:notice] = "article was successfully updated"
      redirect_to alpha_path(@alpha)
    else
      render 'edit'
    end
  end

  # DELETE /alphas/1
  # DELETE /alphas/1.json
  def destroy
    @alpha.destroy
    flash[:notice] = "article was successfully deleted"
    redirect_to alphas_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_alpha
      @alpha = Alpha.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def alpha_params
      params.require(:alpha).permit(:title , :description)
    end
end

app/helpers/alphas_helper.rb
module AlphasHelper
end

app/views/alphas/_form.html.erb
<h3>Following errors prevent alpha getting created</h3>
<% if @alpha.errors.any? %>
  <ul>
    <% @alpha.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>
<%= form_for @alpha do |d| %>
  <p>
    <%= d.label :title %><br/>
    <%= d.text_field :title %>
  </p>
  <p>
    <%= d.label :description %><br/>
    <%= d.text_field :description %>
  </p>
  <p>
    <%= d.submit %>
  </p>
<% end %>
<%= link_to "Back to alpha listing" , alphas_path %>

app/views/alphas/edit.html.erb
<h1>Edit Alpha</h1>
<%= render 'form' %>

app/views/alphas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Alphas</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @alphas.each do |alpha| %>
      <tr>
        <td><%= alpha.title %></td>
        <td><%= alpha.description %></td>
        <td><%= link_to 'Show', alpha %></td>
        <td><%= link_to 'Edit', edit_alpha_path(alpha) %></td>
        <td><%= link_to 'Destroy', alpha, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Alpha', new_alpha_path %>

app/views/alphas/new.html.erb
<h1>New Alpha</h1>
<%= render 'form' %>

app/views/alphas/show.html.erb
<h1>Showing selected alpha</h1>
<p>
  Title: <%= @alpha.title %>
</p>
<p>
  Desription: <%= @alpha.description %>
</p>
<%= link_to "Edit alpha" , edit_alpha_path(@alpha) %> |
<%= link_to "Back to alpha listing" , alphas_path %>